/*
 * Generated by ISE 19.05.10.3187 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F269_6091();
extern void F271_6250();
extern void F265_5893();
extern void F268_6088();
extern void F292_3803();
extern void F291_5773();
extern void F128_1391();
extern EIF_REFERENCE F128_1378();
extern EIF_BOOLEAN F128_1390();
extern EIF_BOOLEAN F128_1398();
extern void F128_1400();
extern void F128_1401();
extern void F128_1402();
extern void F69_1049();
extern EIF_TYPED_VALUE F69_1050();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F269_6091;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F265_5893;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F292_3803;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F271_6250;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F268_6088;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F291_5773;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F128_1391;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F128_1390;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F128_1378;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F128_1398;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F128_1400;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F128_1401;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F128_1402;

	egc_str_dtype = 270;

	egc_str32_dtype = 267;
	egc_arr_dtype = 291;
	egc_tup_dtype = 219;
	egc_disp_rout_id = 2158;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0334;
	egc_sp_wchar = 0x0290;
	egc_sp_bool = 0x01AD;
	egc_sp_uint8 = 0x0274;
	egc_sp_uint16 = 0x02B0;
	egc_sp_uint32 = 0x0225;
	egc_sp_uint64 = 0x0186;
	egc_sp_int8 = 0x0342;
	egc_sp_int16 = 0x0365;
	egc_sp_int32 = 0x0160;
	egc_sp_int64 = 0x0311;
	egc_sp_real32 = 0x02CB;
	egc_sp_real64 = 0x02EE;
	egc_sp_pointer = 0x0247;
	egc_sp_ref = 0x0124;

	egc_uint8_dtype = 239;
	egc_uint16_dtype = 236;
	egc_uint32_dtype = 233;
	egc_uint64_dtype = 230;
	egc_int8_dtype = 227;
	egc_int16_dtype = 224;
	egc_int32_dtype = 254;
	egc_int64_dtype = 221;
	egc_bool_dtype = 257;
	egc_real32_dtype = 242;
	egc_char_dtype = 251;
	egc_wchar_dtype = 248;
	egc_real64_dtype = 245;
	egc_point_dtype = 260;

	egc_exception_dtype = 87;
	egc_except_emnger_dtype = 127;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "wsf_markup";
	egc_system_location = "C:\\Users\\LJR19\\OneDrive\\Documents\\GitHub\\wsf_markup\\EIFGENs\\test\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1560005947;
	egc_has_old_special_semantic = 0;
	scount = 984;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "ANY.default_create";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 32;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2723;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 4891;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 68;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F69_1049;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F69_1050;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 0; /* ANY */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 190; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 282; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
